version: "3.8"
services:
  postgres:
    env_file:
      - ".env"
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready","-U","${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: ghcr.io/persianccbook/backend:latest
    env_file:
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["gunicorn", "--workers=3", "--bind=0.0.0.0:8000", "core.wsgi:application"]
  frontend:
    image: ghcr.io/persianccbook/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
